name: Build and Release Module

on:
  workflow_dispatch: # 允许手动触发
  push:
    tags:
      - 'v*' # 当推送 v 开头的 tag 时触发，例如 v1.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 需要写入 releases 的权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from module.prop
        id: version
        run: |
          if [ -f "module.prop" ]; then
            echo "Reading version from module.prop..."
            VERSION=$(grep "^version=" module.prop | cut -d'=' -f2)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "Detect version: $VERSION"
          else
            echo "module.prop not found!"
            exit 1
          fi

      - name: Zip module
        run: |
          # 定义文件名，例如 TProxyShell-v1.0.zip
          ZIP_NAME="TProxyShell-${{ env.VERSION }}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          
          # 打包所有文件，排除 .git, .github 目录和 README 等无关文件
          zip -r "$ZIP_NAME" . -x ".git/*" ".github/*" ".gitignore" "README.md" "LICENSE" "*.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ZIP_NAME }}
          body: |
            Automatic release for version ${{ env.VERSION }}.
            
            Hash (SHA256):
            `$(sha256sum ${{ env.ZIP_NAME }} | cut -d' ' -f1)`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact (For manual runs)
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}          # 排除 git 相关文件和临时文件
          zip -r "$ZIP_NAME" . -x ".git/*" ".github/*" ".gitignore" "README.md" "LICENSE" "*.zip" "bin/readme.md"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ZIP_NAME }}
          body: |
            Automatic release for version ${{ env.VERSION }}.
            Includes latest sing-box binary.
            
            Hash (SHA256):
            `$(sha256sum ${{ env.ZIP_NAME }} | cut -d' ' -f1)`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact (For manual runs)
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}
